INSERT INTO CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT) VALUES(1,'dollar', 'rupees',0.8,8081);
INSERT INTO CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT) VALUES(2,'rupees', 'dollar',80,8081);
INSERT INTO CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT) VALUES(3,'rupees', 'euro',100,8081);
INSERT INTO CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT) VALUES(4,'rupees', 'yen',40,8081);

